name: Build ModList Exporter

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-common:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Build and test common module
      run: ./gradlew :common:build :common:test
      
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [fabric-1.19.4, fabric-1.20.4, fabric-1.21.1]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
      
    - name: Build ${{ matrix.module }}
      run: ./gradlew :${{ matrix.module }}:build
      
    - name: List built artifacts
      run: ls -la ${{ matrix.module }}/build/libs/
      
    - name: Upload ${{ matrix.module }} artifact
      uses: actions/upload-artifact@v4
      with:
        name: modlistexporter-${{ matrix.module }}-${{ github.run_number }}
        path: ${{ matrix.module }}/build/libs/modlistexporter-fabric-mc${{ matrix.module }}*.jar
        retention-days: 30
        
    - name: Upload ${{ matrix.module }} sources
      uses: actions/upload-artifact@v4
      with:
        name: modlistexporter-${{ matrix.module }}-sources-${{ github.run_number }}
        path: ${{ matrix.module }}/build/libs/modlistexporter-fabric-mc${{ matrix.module }}*-sources.jar
        retention-days: 30
